# AUTO-GENERATED by derive-trusted-key.mjs — do not edit by hand.
# REBUILD rust-core + service, then re-pin (use after changing native code).
# Run from an ELEVATED (Administrator) PowerShell with the desktop app CLOSED.
$ErrorActionPreference = 'Stop'
Set-Location -LiteralPath 'C:\Users\tan27\OneDrive\Documents\Workspace\Edulearn_NCKH\desktop\edulearn-exam-service'
.\Setup-ExamGuardService.ps1 -TrustedServerKeysJson '{"exam-policy-primary":"ge7dOBhkq+QV+m9A+WeNrL0BbqZIYjfSoVummUg0jMQ="}'
sc.exe query EduLearnExamGuard
